/**
 * Merge Ticketing API
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CommentRequest model module.
 * @module model/CommentRequest
 * @version 1.0
 */
class CommentRequest {
    /**
     * Constructs a new <code>CommentRequest</code>.
     * # The Comment Object ### Description The &#x60;Comment&#x60; object is used to represent a comment on a ticket.  ### Usage Example TODO
     * @alias module:model/CommentRequest
     */
    constructor() { 
        
        CommentRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CommentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CommentRequest} obj Optional instance to populate.
     * @return {module:model/CommentRequest} The populated <code>CommentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommentRequest();

            if (data.hasOwnProperty('remote_id')) {
                obj['remote_id'] = ApiClient.convertToType(data['remote_id'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = ApiClient.convertToType(data['contact'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
            if (data.hasOwnProperty('html_body')) {
                obj['html_body'] = ApiClient.convertToType(data['html_body'], 'String');
            }
            if (data.hasOwnProperty('ticket')) {
                obj['ticket'] = ApiClient.convertToType(data['ticket'], 'String');
            }
            if (data.hasOwnProperty('is_private')) {
                obj['is_private'] = ApiClient.convertToType(data['is_private'], 'Boolean');
            }
            if (data.hasOwnProperty('remote_created_at')) {
                obj['remote_created_at'] = ApiClient.convertToType(data['remote_created_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * The third-party API ID of the matching object.
 * @member {String} remote_id
 */
CommentRequest.prototype['remote_id'] = undefined;

/**
 * @member {String} user
 */
CommentRequest.prototype['user'] = undefined;

/**
 * @member {String} contact
 */
CommentRequest.prototype['contact'] = undefined;

/**
 * The comment's text body.
 * @member {String} body
 */
CommentRequest.prototype['body'] = undefined;

/**
 * The comment's text body formatted as html.
 * @member {String} html_body
 */
CommentRequest.prototype['html_body'] = undefined;

/**
 * @member {String} ticket
 */
CommentRequest.prototype['ticket'] = undefined;

/**
 * Whether or not the comment is internal.
 * @member {Boolean} is_private
 */
CommentRequest.prototype['is_private'] = undefined;

/**
 * When the third party's comment was created.
 * @member {Date} remote_created_at
 */
CommentRequest.prototype['remote_created_at'] = undefined;






export default CommentRequest;

