/**
 * Merge Ticketing API
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TicketStatusEnum from './TicketStatusEnum';

/**
 * The TicketRequest model module.
 * @module model/TicketRequest
 * @version 1.0
 */
class TicketRequest {
    /**
     * Constructs a new <code>TicketRequest</code>.
     * # The Ticket Object ### Description The &#x60;Ticket&#x60; object is used to represent a ticket or a task within a system.  ### Usage Example TODO
     * @alias module:model/TicketRequest
     */
    constructor() { 
        
        TicketRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TicketRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TicketRequest} obj Optional instance to populate.
     * @return {module:model/TicketRequest} The populated <code>TicketRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TicketRequest();

            if (data.hasOwnProperty('remote_id')) {
                obj['remote_id'] = ApiClient.convertToType(data['remote_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('assignees')) {
                obj['assignees'] = ApiClient.convertToType(data['assignees'], ['String']);
            }
            if (data.hasOwnProperty('due_date')) {
                obj['due_date'] = ApiClient.convertToType(data['due_date'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], TicketStatusEnum);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ApiClient.convertToType(data['project'], 'String');
            }
            if (data.hasOwnProperty('ticket_type')) {
                obj['ticket_type'] = ApiClient.convertToType(data['ticket_type'], 'String');
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('contact')) {
                obj['contact'] = ApiClient.convertToType(data['contact'], 'String');
            }
            if (data.hasOwnProperty('parent_ticket')) {
                obj['parent_ticket'] = ApiClient.convertToType(data['parent_ticket'], 'String');
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], ['String']);
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], ['String']);
            }
            if (data.hasOwnProperty('remote_created_at')) {
                obj['remote_created_at'] = ApiClient.convertToType(data['remote_created_at'], 'Date');
            }
            if (data.hasOwnProperty('remote_updated_at')) {
                obj['remote_updated_at'] = ApiClient.convertToType(data['remote_updated_at'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * The third-party API ID of the matching object.
 * @member {String} remote_id
 */
TicketRequest.prototype['remote_id'] = undefined;

/**
 * The ticket's name.
 * @member {String} name
 */
TicketRequest.prototype['name'] = undefined;

/**
 * @member {Array.<String>} assignees
 */
TicketRequest.prototype['assignees'] = undefined;

/**
 * The ticket's due date.
 * @member {Date} due_date
 */
TicketRequest.prototype['due_date'] = undefined;

/**
 * The current status of the ticket.
 * @member {module:model/TicketStatusEnum} status
 */
TicketRequest.prototype['status'] = undefined;

/**
 * The ticket's description.
 * @member {String} description
 */
TicketRequest.prototype['description'] = undefined;

/**
 * @member {String} project
 */
TicketRequest.prototype['project'] = undefined;

/**
 * The ticket's type.
 * @member {String} ticket_type
 */
TicketRequest.prototype['ticket_type'] = undefined;

/**
 * @member {String} account
 */
TicketRequest.prototype['account'] = undefined;

/**
 * @member {String} contact
 */
TicketRequest.prototype['contact'] = undefined;

/**
 * @member {String} parent_ticket
 */
TicketRequest.prototype['parent_ticket'] = undefined;

/**
 * @member {Array.<String>} attachments
 */
TicketRequest.prototype['attachments'] = undefined;

/**
 * @member {Array.<String>} tags
 */
TicketRequest.prototype['tags'] = undefined;

/**
 * When the third party's ticket was created.
 * @member {Date} remote_created_at
 */
TicketRequest.prototype['remote_created_at'] = undefined;

/**
 * When the third party's ticket was updated.
 * @member {Date} remote_updated_at
 */
TicketRequest.prototype['remote_updated_at'] = undefined;






export default TicketRequest;

