/**
 * Merge Ticketing API
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TicketStatusEnum.
* @enum {}
* @readonly
*/
export default class TicketStatusEnum {
    
        /**
         * value: "OPEN"
         * @const
         */
        "OPEN" = "OPEN";

    
        /**
         * value: "CLOSED"
         * @const
         */
        "CLOSED" = "CLOSED";

    

    /**
    * Returns a <code>TicketStatusEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TicketStatusEnum} The enum <code>TicketStatusEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

