/**
 * Merge Ticketing API
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeTicketingApi);
  }
}(this, function(expect, MergeTicketingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeTicketingApi.MultipartFormFieldRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MultipartFormFieldRequest', function() {
    it('should create an instance of MultipartFormFieldRequest', function() {
      // uncomment below and update the code to test MultipartFormFieldRequest
      //var instane = new MergeTicketingApi.MultipartFormFieldRequest();
      //expect(instance).to.be.a(MergeTicketingApi.MultipartFormFieldRequest);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MergeTicketingApi.MultipartFormFieldRequest();
      //expect(instance).to.be();
    });

    it('should have the property data (base name: "data")', function() {
      // uncomment below and update the code to test the property data
      //var instance = new MergeTicketingApi.MultipartFormFieldRequest();
      //expect(instance).to.be();
    });

    it('should have the property encoding (base name: "encoding")', function() {
      // uncomment below and update the code to test the property encoding
      //var instance = new MergeTicketingApi.MultipartFormFieldRequest();
      //expect(instance).to.be();
    });

    it('should have the property file_name (base name: "file_name")', function() {
      // uncomment below and update the code to test the property file_name
      //var instance = new MergeTicketingApi.MultipartFormFieldRequest();
      //expect(instance).to.be();
    });

    it('should have the property content_type (base name: "content_type")', function() {
      // uncomment below and update the code to test the property content_type
      //var instance = new MergeTicketingApi.MultipartFormFieldRequest();
      //expect(instance).to.be();
    });

  });

}));
