/**
 * Merge Ticketing API
 * The unified API for building rich integrations with multiple Ticketing platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MergeTicketingApi);
  }
}(this, function(expect, MergeTicketingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MergeTicketingApi.TicketRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TicketRequest', function() {
    it('should create an instance of TicketRequest', function() {
      // uncomment below and update the code to test TicketRequest
      //var instane = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be.a(MergeTicketingApi.TicketRequest);
    });

    it('should have the property remote_id (base name: "remote_id")', function() {
      // uncomment below and update the code to test the property remote_id
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property assignees (base name: "assignees")', function() {
      // uncomment below and update the code to test the property assignees
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property due_date (base name: "due_date")', function() {
      // uncomment below and update the code to test the property due_date
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property project (base name: "project")', function() {
      // uncomment below and update the code to test the property project
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property ticket_type (base name: "ticket_type")', function() {
      // uncomment below and update the code to test the property ticket_type
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property account (base name: "account")', function() {
      // uncomment below and update the code to test the property account
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property contact (base name: "contact")', function() {
      // uncomment below and update the code to test the property contact
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property parent_ticket (base name: "parent_ticket")', function() {
      // uncomment below and update the code to test the property parent_ticket
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property attachments (base name: "attachments")', function() {
      // uncomment below and update the code to test the property attachments
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property remote_created_at (base name: "remote_created_at")', function() {
      // uncomment below and update the code to test the property remote_created_at
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

    it('should have the property remote_updated_at (base name: "remote_updated_at")', function() {
      // uncomment below and update the code to test the property remote_updated_at
      //var instance = new MergeTicketingApi.TicketRequest();
      //expect(instance).to.be();
    });

  });

}));
